<#
.SYNOPSIS
  Create a new Pragma batch session: its own memory, its own workspace.

.DESCRIPTION
  `start.bat` opens the normal interface. This is the batch counterpart: it
  sets up a folder that holds one persistent memory and gives you a `pragma`
  command to work with it from PowerShell.

  Each session is independent. A session for your notes and a session for a
  project remember different things and never mix.

  The folder it creates:

      <path>\
          pragma.ps1     enter the session:  . <path>\pragma.ps1
          workspace\     the files the agent reads and writes
          .memoria\      episodes and beliefs
          backups\       created by `pragma -Backup`

  Only pragma.ps1 is generated: the commands themselves live in the repository
  (tools\pragma-session.ps1), so a session picks up improvements the next time
  you enter it.

  Run with no arguments for the guided version; pass the parameters to skip
  the questions.

.EXAMPLE
  .\new-session.ps1

.EXAMPLE
  .\new-session.ps1 -Path D:\pragma-notes -Name notes -Profile 27b
#>

[CmdletBinding()]
param(
    # Where the session lives. Anywhere outside the Pragma repository.
    [string]$Path,

    # Short name, used in the banner and to confirm a wipe. Defaults to the
    # folder name.
    [string]$Name,

    # A profile from examples_memory\models.json. Empty = the model in .env.
    [string]$Profile,

    # Step budget for one task.
    [int]$MaxSteps = 50,

    # native = the model calls tools and the server constrains the arguments
    # with a grammar (recommended). text = the older channel, kept so earlier
    # results can be reproduced.
    [ValidateSet('native', 'text')]
    [string]$Protocol = 'native',

    # Overwrite an existing pragma.ps1 in that folder.
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$Repo = $PSScriptRoot

function Ask([string]$question, [string]$default) {
    $suffix = if ($default) { " [$default]" } else { "" }
    $reply = Read-Host "  $question$suffix"
    if ([string]::IsNullOrWhiteSpace($reply)) { return $default }
    return $reply.Trim()
}

Write-Host ""
Write-Host "New Pragma batch session" -ForegroundColor Cyan
Write-Host "  repository : $Repo"

# --- the Python environment has to exist before anything else ----------------
$py = Join-Path $Repo "venv\Scripts\python.exe"
if (-not (Test-Path $py)) {
    Write-Host ""
    Write-Host "Python environment not found at $py" -ForegroundColor Red
    Write-Host "Run install.bat first, then come back."
    exit 1
}

# --- questions ----------------------------------------------------------------
Write-Host ""
if (-not $Path) {
    $Path = Ask "Where should this session live?" (Join-Path $HOME "pragma-notes")
}
$Path = [System.IO.Path]::GetFullPath($Path)

# A session inside the repository would put the agent's workspace in Pragma's
# own source tree, which agent.batch refuses outright - catch it here, with an
# explanation, instead of at the first task.
if ($Path.ToLower().StartsWith($Repo.ToLower())) {
    Write-Host ""
    Write-Host "That path is inside the Pragma repository." -ForegroundColor Red
    Write-Host "A session must live elsewhere: Pragma refuses to work inside its own"
    Write-Host "source tree, and keeping your data out of it also keeps it out of git."
    exit 1
}

# Checked before the remaining questions: being asked for a name and a profile
# only to be told the session already existed is a waste of the user's time.
$sessionFile = Join-Path $Path "pragma.ps1"
if ((Test-Path $sessionFile) -and -not $Force) {
    Write-Host ""
    Write-Host "A session already exists at $sessionFile" -ForegroundColor Yellow
    Write-Host "Enter it with:   . $sessionFile"
    Write-Host "Re-create it with -Force (your memory is NOT touched)."
    exit 1
}

if (-not $Name) {
    $Name = Ask "A short name for it?" (Split-Path $Path -Leaf)
}
if (-not $PSBoundParameters.ContainsKey('Profile')) {
    $Profile = Ask "Model profile (empty = the model from .env)?" ""
}

# --- create ---------------------------------------------------------------------
foreach ($d in @($Path, (Join-Path $Path "workspace"), (Join-Path $Path ".memoria"))) {
    New-Item -ItemType Directory -Force $d | Out-Null
}

$stamp = Get-Date -Format "yyyy-MM-dd"
$lines = @(
    "# pragma.ps1 - Pragma batch session '$Name'",
    "# Generated by new-session.ps1 on $stamp. Safe to edit by hand.",
    "#",
    "# Enter this session:",
    "#     . $sessionFile",
    "#",
    "# Then:  pragma `"your task`"      |      pragma -Info  for every command",
    "#",
    "# NOTE: keep this file pure ASCII - PowerShell 5.1 reads BOM-less files as",
    "# ANSI, and a fancy dash or quote silently corrupts the script.",
    "",
    "`$PragmaSession = @{",
    "    Name     = `"$Name`"",
    "    Root     = `"$Path`"",
    "    Repo     = `"$Repo`"",
    "    Profile  = `"$Profile`"        # `"`" = the model from the repo .env",
    "    MaxSteps = $MaxSteps",
    "    Protocol = `"$Protocol`"    # native | text",
    "",
    "    # Output budgets. `"`" = whatever the repository defaults to, which is",
    "    # the right answer unless you know your server needs otherwise.",
    "    # ContextWindow MUST match the -c of your LLM server if you set it.",
    "    ContextWindow  = `"`"",
    "    MaxTokens      = `"`"",
    "    SkillMaxTokens = `"`"",
    "    Timeout        = `"`"",
    "}",
    "",
    ". (Join-Path `$PragmaSession.Repo `"tools\pragma-session.ps1`")"
)
# ASCII, no BOM: PowerShell 5.1 would otherwise read the file as ANSI and the
# first line would carry invisible bytes.
Set-Content -Path $sessionFile -Value $lines -Encoding ASCII

# PRAGMA.md - standing instructions, injected before EVERY task in this
# workspace. Shipped as comments only, so it stays inert until someone writes
# a real rule: the agent ignores HTML comments, and a file with nothing else
# in it is treated as absent.
$contractFile = Join-Path $Path "workspace\PRAGMA.md"
if (-not (Test-Path $contractFile)) {
    $contract = @(
        "<!--",
        "PRAGMA.md - standing instructions for this workspace.",
        "",
        "Anything you write OUTSIDE these comment markers is given to the agent",
        "before every task, on top of whatever it remembers. Use it for rules",
        "that always apply, not for one-off requests.",
        "",
        "The agent may read this file and can never write to it.",
        "",
        "Comments like this one are ignored, so this guidance costs you nothing.",
        "Write your rules below the closing marker, for example:",
        "",
        "    ## Environment",
        "    - Install every dependency in .\venv, never in system Python.",
        "    - Run Python through .\venv\Scripts\python.exe.",
        "",
        "    ## Conventions",
        "    - Tests live in tests\ and run with pytest.",
        "    - Never edit anything under generated\.",
        "",
        "    ## Standing authorizations",
        "    - Deleting files under tmp\ is pre-authorized.",
        "",
        "Memory is what the agent LEARNS; this file is what you DECIDE. A rule",
        "here is never weighed against other memories - it always applies.",
        "-->"
    )
    Set-Content -Path $contractFile -Value $contract -Encoding ASCII
}

Write-Host ""
Write-Host "Created $sessionFile" -ForegroundColor Green
Write-Host "  memory    : $(Join-Path $Path '.memoria')"
Write-Host "  workspace : $(Join-Path $Path 'workspace')"
Write-Host "  rules     : $contractFile" -ForegroundColor Cyan
Write-Host "              standing instructions, read before EVERY task."
Write-Host "              Empty for now - open it and write what must always hold."

# --- is the backend up? a warning here saves a confusing first task ------------
Push-Location $Repo
$served = & $py -c @"
import sys
sys.path.insert(0, 'core')
import llm_client
ok, d = llm_client.ping_models()
print(('OK|' if ok else 'DOWN|') + d)
"@ 2>&1
Pop-Location
if (("$served" -split '\|')[0] -eq "OK") {
    Write-Host "  backend   : OK" -ForegroundColor Green
} else {
    Write-Host "  backend   : DOWN - start your LLM server before the first task" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Enter the session with:" -ForegroundColor Cyan
Write-Host "    . $sessionFile"
Write-Host ""
