#!/usr/bin/env python3
# Copyright (C) 2026 Homo Agens
# SPDX-License-Identifier: AGPL-3.0-or-later
# This file is part of Pragma <https://github.com/homoagens/pragma>.

"""Build the generated reference pages, or check that they are still true.

    python docs/build.py            write the pages
    python docs/build.py --check    change nothing; exit 1 if a page is out
                                    of date, a setting has no description,
                                    a link in the docs points nowhere, or a
                                    page is missing from the site's menu

WHY THESE PAGES ARE GENERATED. A list of settings written by hand is right on
the day it is written. The code reads ninety-odd environment variables and the
example file named three of them; the commands had been reorganised twice
since anyone listed them. What the code already knows - which variables it
reads and their defaults, which commands exist, which skills are offered - is
therefore read FROM the code, every time, and CI runs --check so that a page
cannot fall behind the thing it describes.

WHAT IS STILL WRITTEN BY HAND is what the code cannot say: what a setting is
for. That is docs/notes.py, one line each, and the two are held together: a
variable with no description stops the build, and so does a description of a
variable nothing reads any more.

NOTHING HERE IMPORTS PRAGMA. The sources are parsed, not run, so this works
without the virtual environment, without a .env and without a model server -
which is what lets CI run it, and what keeps a page from depending on the
machine that built it.

    reference/configuration.md   every environment variable the code reads
    reference/commands.md        the commands of the two screens
    reference/skills.md          the tools, and which of them the agent is given
"""

from __future__ import annotations

import ast
import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
REF = DOCS / "reference"

BANNER = ("<!-- Generated by docs/build.py. Do not edit this page: change the code, "
          "or docs/notes.py,\n     and run `python docs/build.py`. -->\n")

COMPUTED = object()         # a default the code works out from other settings


class Stop(Exception):
    """Something the pages cannot be built from. The message says what to fix."""


# ── reading the code without running it ──────────────────────────────────────

def _read(path: Path) -> str:
    # utf-8-sig: one of the sources starts with a byte-order mark, which
    # Python's own loader forgives and ast.parse does not.
    return path.read_text(encoding="utf-8-sig")


def _rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _sources() -> list[Path]:
    """The Python the harness actually runs.

    Not the retired skills: a folder under core/skills whose name starts with
    an underscore is never loaded, so a variable read only there is not a
    setting. Not the wip_ ones either - they are in nobody else's checkout.
    """
    out = []
    for top in ("core", "agent", "tools"):
        for path in sorted((ROOT / top).rglob("*.py")):
            parts = path.relative_to(ROOT).parts
            if any(p.startswith(("_", "wip_")) and p != "__init__.py" for p in parts[:-1]):
                continue
            out.append(path)
    return out


def tables(path: Path, names: set[str]) -> dict:
    """The value of some module-level tables, without importing the module.

    Only the statements that build them are run - the assignment, and any
    `TABLE.update(...)` after it - in a namespace with no builtins. A table
    that turns out to need the rest of its module fails here, by name, which
    is the moment to stop reading it this way.
    """
    tree = ast.parse(_read(path))
    ns: dict = {"__builtins__": {}}
    for node in tree.body:
        targets: list[str] = []
        if isinstance(node, ast.Assign):
            targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            targets = [node.target.id]
        elif isinstance(node, ast.Expr) and isinstance(node.value, ast.Call):
            fn = node.value.func
            if (isinstance(fn, ast.Attribute) and fn.attr == "update"
                    and isinstance(fn.value, ast.Name)):
                targets = [fn.value.id]
        if not any(t in names for t in targets):
            continue
        module = ast.Module(body=[node], type_ignores=[])
        try:
            exec(compile(module, str(path), "exec"), ns)
        except Exception as e:
            raise Stop(f"{_rel(path)}:{node.lineno}: cannot read {targets[0]} "
                       f"on its own ({e.__class__.__name__}: {e})")
    missing = sorted(n for n in names if n not in ns)
    if missing:
        raise Stop(f"{_rel(path)}: no table called {', '.join(missing)}")
    return {n: ns[n] for n in names}


def pairs(path: Path, name: str) -> list[tuple[str, str]]:
    """The first two strings of each row of a list of tuples.

    For the tables whose rows end in a function - (name, blurb, handler) -
    which cannot be evaluated without the module around them.
    """
    for node in ast.parse(_read(path)).body:
        if (isinstance(node, ast.Assign) and len(node.targets) == 1
                and isinstance(node.targets[0], ast.Name)
                and node.targets[0].id == name
                and isinstance(node.value, (ast.List, ast.Tuple))):
            out = []
            for row in node.value.elts:
                if isinstance(row, ast.Tuple) and len(row.elts) >= 2 and all(
                        isinstance(e, ast.Constant) and isinstance(e.value, str)
                        for e in row.elts[:2]):
                    out.append((row.elts[0].value, row.elts[1].value))
            return out
    raise Stop(f"{_rel(path)}: no list called {name}")


# ── the settings ─────────────────────────────────────────────────────────────

_GETTERS = ("os.environ.get", "os.getenv", "environ.get")
_HELPERS = ("_opt_float", "_opt_int")        # config.py's own: name in, number out


def _default(call: ast.Call, parents: dict):
    """What a read falls back to: a string, None for nothing, or COMPUTED."""
    given = call.args[1] if len(call.args) > 1 else None
    if given is not None:
        if not isinstance(given, ast.Constant):
            return COMPUTED
        if given.value not in ("", None):
            return str(given.value)
    # Empty or absent, and then `... or 42` right behind it: that is the
    # default, spelled the other way.
    parent = parents.get(call)
    if (isinstance(parent, ast.BoolOp) and isinstance(parent.op, ast.Or)
            and parent.values and parent.values[0] is call):
        after = parent.values[1]
        return str(after.value) if isinstance(after, ast.Constant) else COMPUTED
    return None


def environment() -> dict[str, list[tuple[str, object]]]:
    """{variable: [(file, default), ...]} for every variable the code reads."""
    found: dict[str, list[tuple[str, object]]] = {}
    for path in _sources():
        tree = ast.parse(_read(path))
        parents = {child: node for node in ast.walk(tree)
                   for child in ast.iter_child_nodes(node)}
        for node in ast.walk(tree):
            name, default = None, None
            if isinstance(node, ast.Call) and node.args:
                first = node.args[0]
                literal = (first.value if isinstance(first, ast.Constant)
                           and isinstance(first.value, str) else None)
                fn = ast.unparse(node.func)
                if literal and fn in _GETTERS:
                    name, default = literal, _default(node, parents)
                elif literal and fn in _HELPERS:
                    name = literal
            elif (isinstance(node, ast.Subscript) and isinstance(node.ctx, ast.Load)
                    and ast.unparse(node.value) == "os.environ"
                    and isinstance(node.slice, ast.Constant)
                    and isinstance(node.slice.value, str)):
                name = node.slice.value
            if name:
                found.setdefault(name, []).append((_rel(path), default))
    # config.py first: where it reads a variable, that read is the definition
    # and the others are copies of it.
    for sites in found.values():
        sites.sort(key=lambda s: (s[0] != "core/config.py", s[0]))
    return found


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _said(text: str) -> str:
    """A line of help taken from the code, safe in a table.

    `/open <name>` is how the screens say it, and in Markdown a bare <name>
    is a tag: it would render as nothing.
    """
    return _cell(text).replace("<", "&lt;").replace(">", "&gt;")


def configuration(notes) -> str:
    env = environment()
    described = dict(notes.CONFIG)
    read = {name for name in env if name not in notes.NOT_PRAGMA}

    problems = []
    for name in sorted(read - set(described)):
        problems.append(f"{name} is read in {env[name][0][0]} and has no line in docs/notes.py")
    for name in sorted(set(described) - read):
        problems.append(f"{name} is described in docs/notes.py and nothing reads it any more")
    groups = [key for key, _, _ in notes.CONFIG_GROUPS]
    for name, entry in sorted(described.items()):
        if entry[0] not in groups:
            problems.append(f"{name} is filed under '{entry[0]}', which is not a group")
    if problems:
        raise Stop("settings and their descriptions disagree:\n  " + "\n  ".join(problems))

    setting_of = {var: key for key, var in tables(
        ROOT / "tools" / "pragma_launcher.py", {"ENV_OF"})["ENV_OF"].items()}

    out = [BANNER, "# Configuration\n", notes.CONFIG_INTRO.rstrip()]
    for key, title, lead in notes.CONFIG_GROUPS:
        names = [n for n, e in described.items() if e[0] == key]
        if not names:
            continue
        out.append(f"\n## {title}\n")
        if lead:
            out.append(lead + "\n")
        out.append("| Variable | Default | What it is | Read in |")
        out.append("|---|---|---|---|")
        for name in names:                          # the order written in notes.py
            entry = described[name]
            text = entry[1]
            if name in setting_of:
                text += f" *Project setting `{setting_of[name]}`.*"
            if len(entry) > 2:
                default = entry[2]
            else:
                found = env[name][0][1]
                if found is COMPUTED:
                    raise Stop(f"{name}: its default is worked out from other settings. "
                               f"Say what it comes to, as a third element, in docs/notes.py")
                default = "unset" if found is None else f"`{found}`"
            files = list(dict.fromkeys(site for site, _ in env[name]))
            where = ", ".join(f"[`{f}`](../../{f})" for f in files)
            out.append(f"| `{name}` | {_cell(default)} | {_cell(text)} | {where} |")
    return "\n".join(out).rstrip() + "\n"


# ── the commands ─────────────────────────────────────────────────────────────

def _rows(head: tuple[str, str], rows) -> list[str]:
    out = [f"| {head[0]} | {head[1]} |", "|---|---|"]
    out += [f"| {a} | {_said(b)} |" for a, b in rows]
    return out


def commands(notes) -> str:
    home_py = ROOT / "tools" / "pragma_home.py"
    chat_py = ROOT / "agent" / "chat.py"
    conf_py = ROOT / "tools" / "pragma_configure.py"

    home = tables(home_py, {"COMMANDS", "PROJECT_ACTIONS", "ALIASES"})
    chat = tables(chat_py, {"_COMMANDS", "_MEMORY_VIEWS", "_VIEW_ALIASES",
                            "_AT_HOME", "_ALIASES"})
    conf = tables(conf_py, {"ROLE_BLURB", "OPTION_BLURB"})
    actions = pairs(conf_py, "ACTIONS")
    endpoint_actions = pairs(conf_py, "ENDPOINT_ACTIONS")

    out = [BANNER, "# Commands\n",
           "Pragma is two screens, and each has its own short list. A command "
           "starts with `/`; anything else typed inside a project is said to "
           "the agent.\n",
           f"Read from [`{_rel(home_py)}`](../../{_rel(home_py)}), "
           f"[`{_rel(chat_py)}`](../../{_rel(chat_py)}) and "
           f"[`{_rel(conf_py)}`](../../{_rel(conf_py)}).\n"]

    out.append("## At home\n")
    out.append("Where no project is open: what is done *to* a project lives here.\n")
    rows = []
    for name, blurb in home["COMMANDS"].items():
        if name == "/projects":
            blurb = "everything done to a project: " + ", ".join(
                f"`{a}`" for a in home["PROJECT_ACTIONS"])
        rows.append((f"`{name}`", blurb))
    out += _rows(("Command", "What it does"), rows)

    out.append("\n### `/projects`\n")
    out.append("Alone it opens the page; followed by one of these it goes straight there.\n")
    out += _rows(("Action", "What it does"),
                 ((f"`{a}`", b) for a, b in home["PROJECT_ACTIONS"].items()))

    out.append("\n## Inside a project\n")
    rows = []
    for name, (_, blurb) in chat["_COMMANDS"].items():
        if name == "/memory":
            blurb = "look at the store: " + ", ".join(f"`{v}`" for v in chat["_MEMORY_VIEWS"])
        rows.append((f"`{name}`", blurb))
    out += _rows(("Command", "What it does"), rows)

    out.append("\n### `/memory`\n")
    out.append("Alone it shows `map`.\n")
    out += _rows(("View", "What it shows"),
                 ((f"`{v}`", b) for v, b in chat["_MEMORY_VIEWS"].items()))

    out.append("\n### Commands that live at home\n")
    out.append("These belong to the home screen. Typed inside a project they "
               "say where they went instead of failing.\n")
    out += _rows(("Command", "At home it is"),
                 ((f"`{n}`", b) for n, b in chat["_AT_HOME"].items()))

    out.append("\n## `/configure`\n")
    out.append("Reached from either screen. A page walked with the arrows "
               "rather than typed.\n")
    rows = []
    for name, blurb in actions:
        if name in conf["OPTION_BLURB"]:
            blurb = "on or off: " + conf["OPTION_BLURB"][name]
        rows.append((f"`{name}`", blurb))
    out += _rows(("Choice", "What it is"), rows)
    out.append("\nUnder `endpoints`, for the one selected:\n")
    out += _rows(("Choice", "What it is"), ((f"`{n}`", b) for n, b in endpoint_actions))
    out.append("\nAn endpoint serves one or more of four roles:\n")
    out += _rows(("Role", "The calls it answers"),
                 ((f"`{r}`", b) for r, b in conf["ROLE_BLURB"].items()))

    out.append("\n## Keys\n")
    out += _rows(("Key", "What it does"), notes.KEYS)

    out.append("\n## Older names\n")
    out.append("Offered by no list, and still working: a habit is not worth breaking.\n")
    rows = [(f"`{old}`", f"`{new}`", "at home") for old, new in home["ALIASES"].items()]
    rows += [(f"`{old}`", f"`{new}`", "in a project") for old, new in chat["_ALIASES"].items()]
    out.append("| Typed | Runs | Where |")
    out.append("|---|---|---|")
    out += [f"| {a} | {b} | {c} |" for a, b, c in rows]
    return "\n".join(out).rstrip() + "\n"


# ── the skills ───────────────────────────────────────────────────────────────

def _signature(path: Path, name: str) -> str:
    """`name(arg, option=default)`, as the loader shows it to the model."""
    for node in ast.parse(_read(path)).body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == name:
            a = node.args
            plain = a.posonlyargs + a.args
            defaults = [None] * (len(plain) - len(a.defaults)) + list(a.defaults)
            parts = []
            for arg, default in zip(plain, defaults):
                parts.append(arg.arg if default is None else f"{arg.arg}={_short(default)}")
            if a.vararg:
                parts.append("*" + a.vararg.arg)
            for arg, default in zip(a.kwonlyargs, a.kw_defaults):
                parts.append(arg.arg if default is None else f"{arg.arg}={_short(default)}")
            if a.kwarg:
                parts.append("**" + a.kwarg.arg)
            return f"{name}({', '.join(parts)})"
    return f"{name}(...)"


def _short(node: ast.AST) -> str:
    text = ast.unparse(node)
    return text if len(text) <= 24 else text[:21] + "..."


def _summary(readme: Path) -> str:
    """What a skill does: the first paragraph under the README's title.

    The whole paragraph, where the loader takes its first line: a summary
    wrapped over two lines reaches the system prompt cut in half, and a page
    for people has no reason to repeat that. A letter in brackets in front of
    it is an older classification and is dropped.
    """
    if not readme.exists():
        return ""
    paragraph: list[str] = []
    for line in _read(readme).split("---")[0].splitlines():
        line = line.strip()
        if line.startswith("#"):
            continue
        if not line:
            if paragraph:
                break
            continue
        paragraph.append(line)
    return re.sub(r"^\[[A-Z]\]\s+", "", " ".join(paragraph))


def skills(notes) -> str:
    base = ROOT / "core" / "skills"
    rules = tables(base / "__init__.py", {"_NOT_AGENT_TOOLS", "_SHELL_DOES_THIS_BETTER"})
    internal = set(rules["_NOT_AGENT_TOOLS"])
    shell = set(rules["_SHELL_DOES_THIS_BETTER"])

    offered, withheld = [], []
    for folder in sorted(base.iterdir()):
        if not folder.is_dir() or folder.name.startswith(("_", "wip_")):
            continue
        if not (folder / "skill.py").exists():
            continue
        name = folder.name
        link = f"[`{name}`](../../core/skills/{name}/README.md)"
        row = (link, _summary(folder / "README.md"),
               "`" + _cell(_signature(folder / "skill.py", name)) + "`")
        if name in internal:
            withheld.append(row)
        else:
            offered.append(row + ("Windows only" if name in shell else "everywhere",))

    out = [BANNER, "# Skills\n",
           "A skill is a tool the agent can call: one folder under "
           "[`core/skills/`](../../core/skills), holding the function and the "
           "README that documents it. The loader finds them by folder; nothing "
           "is registered by hand. To add one, see "
           "[CONTRIBUTING](../../CONTRIBUTING.md) and the "
           "[template](../../core/skills/_template/README.md).\n",
           "Each name links to its README, which has the parameters, what comes "
           "back and examples.\n"]

    left = sum(1 for row in offered if row[3] == "Windows only")
    out.append("## Offered to the agent\n")
    out.append(f"On Linux and macOS {left} of these {len(offered)} are left to the "
               "shell, which does the same job in one call: they are marked "
               "*Windows only*.\n")
    out.append("| Skill | What it does | Call | Offered |")
    out.append("|---|---|---|---|")
    out += [f"| {a} | {_cell(b)} | {c} | {d} |" for a, b, c, d in offered]

    out.append("\n## Used by the harness, never offered\n")
    out.append("The memory is read and written by Pragma around a turn, not by "
               "the agent inside one. These live beside the skills because they "
               "are loaded the same way.\n")
    out.append("| Skill | What it does | Call |")
    out.append("|---|---|---|")
    out += [f"| {a} | {_cell(b)} | {c} |" for a, b, c in withheld]

    out.append("\n## In the tree and not loaded\n")
    out.append("A folder whose name starts with an underscore is skipped by the loader.\n")
    for folder, what in (("_legacy", "retired"), ("_future", "kept for later")):
        names = sorted(p.name for p in (base / folder).iterdir()
                       if p.is_dir() and (p / "skill.py").exists())
        listed = ", ".join(f"`{n}`" for n in names)
        out.append(f"- [`{folder}/`](../../core/skills/{folder}/README.md), {what}: {listed}")
    out.append("- [`_template/`](../../core/skills/_template/README.md), the starting "
               "point for a new one")
    return "\n".join(out).rstrip() + "\n"


# ── the links ────────────────────────────────────────────────────────────────

_FENCE = re.compile(r"^(```|~~~).*?^\1\s*$", re.S | re.M)
_LINK = re.compile(r"(?<!\!)\[[^\]]*\]\(\s*([^)\s]+)[^)]*\)")
_HEADING = re.compile(r"^#{1,6}\s+(.*?)\s*#*\s*$", re.M)


def _anchors(text: str) -> set[str]:
    """The anchors GitHub gives the headings of a page."""
    out = set()
    for title in _HEADING.findall(_FENCE.sub("", text)):
        title = re.sub(r"[`*_]", "", title).strip().lower()
        slug = re.sub(r"[^\w\- ]", "", title).replace(" ", "-")
        out.add(slug)
    return out


def links() -> list[str]:
    """Every link in the docs that points at a file or a heading that is not there."""
    pages = [ROOT / "README.md", ROOT / "CONTRIBUTING.md"] + sorted(DOCS.rglob("*.md"))
    broken = []
    for page in pages:
        if not page.exists():
            continue
        text = _FENCE.sub("", _read(page))
        for target in _LINK.findall(text):
            if re.match(r"[a-z][a-z0-9+.-]*:", target, re.I):
                continue                                    # http:, mailto:
            path, _, anchor = target.partition("#")
            dest = (page.parent / path).resolve() if path else page
            if not dest.exists():
                broken.append(f"{_rel(page)}: {target} - no such file")
            elif anchor and dest.suffix == ".md" and anchor.lower() not in _anchors(_read(dest)):
                broken.append(f"{_rel(page)}: {target} - no such heading")
    return broken


def menu() -> list[str]:
    """Pages the site's menu does not list.

    mkdocs.yml names every page. One left out is still built, and reachable
    by nobody: no menu shows it. Read as text - the name of the file has to
    appear in it - so that this check needs no YAML library.
    """
    config = ROOT / "mkdocs.yml"
    if not config.exists():
        return []
    listed = _read(config)
    return [f"{_rel(page)} is not in the nav of mkdocs.yml"
            for page in sorted(DOCS.rglob("*.md"))
            if page.relative_to(DOCS).as_posix() not in listed]


# ── the build ────────────────────────────────────────────────────────────────

PAGES = {
    "configuration.md": configuration,
    "commands.md": commands,
    "skills.md": skills,
}


def _notes():
    spec = importlib.util.spec_from_file_location("pragma_docs_notes", DOCS / "notes.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main(argv: list[str]) -> int:
    check = "--check" in argv
    try:
        notes = _notes()
        built = {name: make(notes) for name, make in PAGES.items()}
    except Stop as e:
        print(f"docs: {e}", file=sys.stderr)
        return 1

    stale = []
    for name, text in built.items():
        path = REF / name
        have = path.read_bytes().decode("utf-8").replace("\r\n", "\n") if path.exists() else None
        if have == text:
            continue
        stale.append(name)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"docs: wrote reference/{name}")

    broken = links()
    for line in broken:
        print(f"docs: broken link - {line}", file=sys.stderr)
    unlisted = menu()
    for line in unlisted:
        print(f"docs: {line}", file=sys.stderr)
    broken += unlisted

    if check and stale:
        print("docs: out of date - " + ", ".join(f"reference/{n}" for n in stale)
              + "\n      run `python docs/build.py` and commit the result", file=sys.stderr)
    if (check and stale) or broken:
        return 1
    if not stale:
        print("docs: the generated pages are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
